import readPkgUp from 'read-pkg-up'
import path, {join} from 'path'
import fse from 'fs-extra'
import _ from 'lodash'

const {pkg, path: pkgPath} = readPkgUp.sync()

const flowtypedFile = join(process.cwd(), 'flow-typed', 'nodeModules.js.flow')

console.log({flowtypedFile})

const deps = _.merge(pkg.dependencies, pkg.devDependencies)
console.log(deps)

let out = _(deps).map((v, k) => {
  return `declare module '${k}' { declare module.exports: any; }`
}).value().join('\n')

console.log(out)

const comment = '// DO NOT MODIFY: This file is automatically generated by flowtyper to include stubs for all package.json dependencies and devDependencies.\n\n'

out = comment + out

fse.outputFileSync(flowtypedFile, out)

console.log('Written!')

// TODO(vjpr): Ensure that this file is referenced by [libs] or it should be autoamitaclly detetected.
// Warn if `node_modules` is not excluded in flowconfig.
